export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const FETCH_BEACHES = 'FETCH_BEACHES';
export const FETCH_BEACH = 'FETCH_BEACH';
export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const FETCH_ACTIVITY_ITEMS= 'FETCH_ACTIVITY_ITEMS';
export const FETCH_ACTIVITY_ITEM= 'FETCH_ACTIVITY_ITEM';