export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const FETCH_BEACHES = 'FETCH_BEACHES';
export const FETCH_BEACH = 'FETCH_BEACH';

export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const FETCH_ACTIVITY = 'FETCH_ACTIVITY';

export const FETCH_LEARNS = 'FETCH_LEARNS';
export const FETCH_LEARN = 'FETCH_LEARN';

export const FETCH_ESTATE = 'FETCH_ESTATE';
export const FETCH_ESTATES = 'FETCH_ESTATES';

export const FETCH_POINT = 'FETCH_POINT';
export const FETCH_POINTS = 'FETCH_POINTS';

export const FETCH_ACCOMODATIONS = 'FETCH_ACCOMODATIONS';
export const FETCH_ACCOMODATION = 'FETCH_ACCOMODATION';

export const FETCH_SHOP = 'FETCH_SHOP';
export const FETCH_SHOPS = 'FETCH_SHOPS';

export const FETCH_INDIVIDUALS = 'FETCH_INDIVIDUALS';
export const FETCH_INDIVIDUAL = 'FETCH_INDIVIDUAL';

